version: '3.8'
services:
  #django app
  backend_login:
    container_name: skynet_ms_login
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  #eventos de kafka
  cliente_queue:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db
 #postgreSQL
  db:
    image: postgres
    container_name: django_login_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: skynet_login_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql
  #redis
  redis:
    image: redis
    container_name: django_login_api_redis
    ports:
      - 6379:6379

#kafka Queue