# Generated by Django 3.2.16 on 2023-06-06 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20230605_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
