# Generated by Django 3.2.16 on 2023-06-06 08:20

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20230605_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
