# Generated by Django 3.2.16 on 2023-06-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20230606_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_id',
            new_name='id',
        ),
    ]
