# Generated by Django 3.2.16 on 2023-06-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_rename_cliente_id_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicacion'),
        ),
    ]
